### ISSUE TITLE
Create mock gui

### ISSUE THREAD

**Issue by rs333** [rs333/NightmareScheduler#4]
As a developer, I want a mock GUI so I can, have see what the GUI should look like prior to having to implement it in code.

*Acceptance Criteria*
- A mock layout of the GUI screens is created
- The layout is added to this ticket in the comments

**Comment by els410** [comment]
Fxml files are not supported by github comments, so I am creating a branch for review.

**Comment by rs333** [comment]
![image](https://user-images.githubusercontent.com/9875430/181936839-333db7c7-397d-47f4-8a66-1cf74e890e59.png)

![image](https://user-images.githubusercontent.com/9875430/181936858-101d04a0-b0cc-4a24-a2e3-d524520c5abd.png)
